version: '3'
services:
    python.web:
        container_name: 'python-web'
        build:
            context: .
            dockerfile: Dockerfile
        # ports:
        #     - '${APP_PORT:-80}:80'
        volumes:
            - '.:/python-docker'
        networks:
            - python_net
        deploy:
            resources:
                limits:
                    cpus: '0.2'
                    memory: 200M

networks:
    python_net:
        driver: bridge

